# Generated by Django 6.0.5 on 2026-05-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingreso',
            name='talla',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
