# Generated by Django 6.0.5 on 2026-05-20 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_ingreso_precio_ingreso_talla'),
        ('productos', '0004_producto_talla_alter_producto_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
    ]
