# Generated by Django 6.0.5 on 2026-05-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(default=38, max_length=20),
            preserve_default=False,
        ),
    ]
