# Generated by Django 6.0.5 on 2026-05-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_talla_alter_producto_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
