# Generated by Django 6.0.5 on 2026-05-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ARRIENDO', 'ARRIENDO'), ('EMPLEADOS', 'EMPLEADOS'), ('SERVICIOS', 'SERVICIOS'), ('PUBLICIDAD', 'PUBLICIDAD'), ('COMPRAS', 'COMPRAS'), ('OTROS', 'OTROS')], max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
